### ISSUE TITLE
No guid for close event

### ISSUE THREAD

**Issue by Thembelani** [SocketMobile/capturesdk_flutter_snapshot#2]
Hi. 

I am successfully receiving the deviceRemoval event however the guid is not set.

<img width="714" alt="Screenshot 2022-06-07 at 04 11 52" src="https://user-images.githubusercontent.com/6085377/172281023-a85cfa8b-b577-4a47-b8ae-2acad3931e14.png">

`Future<void> _closeDeviceHelper(e, handle) async {
  String guid = e.value.guid;
  String name = e.value.name;
  logger.log('Device Removal =>', name + ' ($guid)');
  try {
    dynamic res = await _deviceCapture!.close();
    if (res == 0) {
      List<DeviceInfo> arr = _devices;
      arr.removeWhere((element) => element.guid == guid);
      setState(() {
        _devices = arr;
        _currentScan = null;
        _deviceCapture = null;
      });
    }
    _updateVals('Device Closed', 'Successfully removed "$name"');
  } on CaptureException catch (exception) {
    _updateVals('${exception.code}', 'Unable to remove "$name"',
        exception.method, exception.details);
  }
}`

**Comment by Thembelani** [comment]
Hi @mcsocket 
The is my code vs the output.
<img width="729" alt="Screenshot 2022-06-08 at 18 39 29" src="https://user-images.githubusercontent.com/6085377/172671196-077b3d67-9ad0-486d-ac1c-7fddce8ce700.png">
<img width="452" alt="Screenshot 2022-06-08 at 18 38 58" src="https://user-images.githubusercontent.com/6085377/172671222-4b62bc0e-71ba-4d96-843b-216ffa8def11.png">

**Comment by Thembelani** [comment]
Hi @mcsocket 

This issue arises when we pair a device that we do not open immediately with the following. 
`dynamic res = await scanner.capture.openDevice(scanner.guid, _capture);` 
or we close a device with the following.
`dynamic res = await scanner.capture.close();`

In both cases, when the device shuts off and deviceRemoval event is fired, e.value.guid returns an empty string. 

If we have a system where more than one device is paired, we should be open and close them while they are still paired.

**Comment by EricGlaenzer** [comment]
I'll have to double check but I think that's expected. When a device is not open in Capture, you will receive a device removal to indicate it's gone, but the guid would be null.
