### ISSUE TITLE
Receive Data Device Info

### ISSUE THREAD

**Issue by Thembelani** [SocketMobile/capturesdk_flutter_snapshot#3]
Hi. 

We are not receiving device information when deviceData gets triggered. Could we please include the device information for the device that performs the scan. 

<img width="714" alt="Screenshot 2022-06-07 at 04 17 17" src="https://user-images.githubusercontent.com/6085377/172283252-c019df06-09b9-4a75-865f-e08787849e59.png">

**Comment by mcsocket** [comment]
Hi @Thembelani,

Currently the handle is present in onCaptureEvent and when the event corresponds to decodedDate, the handle is the handle of the scanning device. If you're storing the devices in your app you can map that handle to corresponding device in the list. 

In the example, we store all connected devices in the state value ` List<DeviceInfo> _devices = [];`. Devices are added to this list after each `deviceArrival` event. This can be found in `_openDeviceHelper`. Devices are removed from the list following each `deviceRemoval` event. This can be found in `_closeDeviceHelper`.  

We plan to incorporate the option for the developer to make use of a deviceList endpoint which retrieves all of the devices with their associated scans in the future. 

Let me know if you need anything else!
